### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/egoless-web#1]
We want to remove the ego from the web. I think starting with twitter makes the most sense, as it is easy to iterate on.

### Things we can do
- [x] Remove stars // hearts // whatever they are, from yourself
- [x] Remove retweets from your messages

### Related

- [ ] Removing retweeted tweets from others
- [ ] Remove the arbitrary timeline

### Goal

To de-gamify the web, and to help us proactively make a better space for listening and being present.

**Comment by hackergrrl** [comment]
Some tech ideas for approaching this:

1. Build an alternative Twitter client. This could be forking an existing open source client and stripping the gamificaton elements.
2. Write extensions for popular browsers. This could be as simple as a set of CSS selectors that set `display: none`.

2 seems the most approachable for a proof of concept. I use Chromium, so that's where I'd like to start. I don't think [it's that complicated](https://blog.lateral.io/2016/04/create-chrome-extension-modify-websites-html-css/) to write this. We could hack it together and see how it feels in use!

Since writing CSS selectors is so simple, this could just be a github repo of rules that anyone can add to for any website. If people are interested in this, we'd be able to build up a pretty extensive database of rules for blocking gamification elements across the web!

**Comment by RichardLitt** [comment]
2) works easiest; let's start with the smallest fruit, go from there. I've been using css rules to ignore things for months - see PR #3. Should have added it earlier, but I've been AFK today .

I think we should add descriptions of why we add a rule when we add it, so that it is clear to everyone from the code itself. See the pull. But yeah; let's go from here, and then move forward. :)

**Comment by hackergrrl** [comment]
What else is included in the mission? Are advertisements ego-ful? (I say they are.)  Are trends ego-ful? (Aye.)  At the very least they disrupt human-to-human interactions by attempting to manipulate our emotional state. I think anything that hinders or tints the content of humans sharing with other humans is suspect.

**Comment by RichardLitt** [comment]
> I think anything that hinders or tints the content of humans sharing with other humans is suspect.

Yes. I don't want to label any particular thing as something to include, but rather stem from that principle. What is likely to engender empathy? What is likely to heighten conversation? What is likely to facilitate good conversation? Remove everything else.

**Comment by hackergrrl** [comment]
Does this issue still apply? Can we close it?

**Comment by RichardLitt** [comment]
Yes!
